Need to extract Lentivirus data from the dataset containing all the viruses.

In [3]:
import pandas as pd

#Taxonomy spreadsheet -> extract all IDs related to lentivirus
taxonomy_keys = pd.read_csv('taxonomy_keys_10239.csv')
print(taxonomy_keys.shape)
taxonomy_keys.head()

(9, 7)

,ScientificName,Rank,UID,nPos,nNeg,nTot,IDs
0,Viruses,superkingdom,10239,6382,10201,16583,"11320,383586,387147,370128,387139,382832,39280..."
1,Riboviria,clade,2559587,4555,8544,13099,"11320,383586,387147,387139,382832,392809,38283..."
2,Pararnavirae,kingdom,2732397,410,188,598,"11780,11908,2169971,10408,10407,35269,11676,11..."
3,Artverviricota,phylum,2732409,410,188,598,"11780,11908,2169971,10408,10407,35269,11676,11..."
4,Revtraviricetes,class,2732514,410,188,598,"11780,11908,2169971,10408,10407,35269,11676,11..."

Retrieve all IDs related to lentivirus

In [4]:
#extract all IDs related to lentivirus
tmp = taxonomy_keys.iloc[8]['IDs']

#remove commas + whitespace + create list
lentivirusID_list = lentivirusID = [id.strip() for id in tmp.split(',')]

#turn string to int
lentivirusID = [int(x) for x in lentivirusID_list]

In [5]:
#Open big dataset -> isolate all rows having lentivirusIDs and save to seperate file
data = pd.read_csv('all_virus_LBCE_with_ESM1b_features.csv', low_memory=False)
data.head()

,Info_PepID,Info_organism_id,Info_protein_id,Info_pos,Info_AA,Info_pubmed_id,Info_epitope_id,Info_host_id,Info_nPos,Info_nNeg,...,feat_esm1b_1270,feat_esm1b_1271,feat_esm1b_1272,feat_esm1b_1273,feat_esm1b_1274,feat_esm1b_1275,feat_esm1b_1276,feat_esm1b_1277,feat_esm1b_1278,feat_esm1b_1279
0,0704243A:2,11320,0704243A,46,S,2579329,61385,10000206,0,2,...,0.074220,-0.306854,-0.046597,0.096433,-1.108830,-0.199020,0.281864,0.003761,0.277273,0.178494
1,0704243A:2,11320,0704243A,47,S,2579329,61385,10000206,0,2,...,0.014104,-0.215472,-0.107374,0.239241,-1.127827,-0.281195,0.344047,0.069742,0.269180,0.259537
2,0704243A:2,11320,0704243A,48,T,2579329,61385,10000206,0,2,...,0.218574,-0.124948,0.082776,0.201489,-0.840510,-0.307259,0.154050,0.100896,0.307250,0.520543
3,0704243A:2,11320,0704243A,49,G,2579329,61385,10000206,0,2,...,0.200644,-0.233248,0.010473,0.070615,-0.804467,-0.219895,0.311264,0.220049,0.131534,0.247521
4,0704243A:2,11320,0704243A,50,K,2579329,61385,10000206,0,2,...,0.103338,-0.239433,0.117235,-0.019795,-1.173937,-0.133920,0.014691,0.156032,0.260330,0.197664

Isolate all Lentivirus data and make new dataset called Lentivirus

In [7]:
#isolate all rows having lentivirusID
lentivirus_data = data[data['Info_organism_id'].isin(lentivirusID)]
#save to seperate file 'lentivirus'
lentivirus_data.to_csv('lentivirus.csv', index=False)

In [5]:
#load lentivus data
lentivirus = pd.read_csv('lentivirus.csv')
#check the size of data
lentivirus.shape
lentivirus.head()

,Info_PepID,Info_organism_id,Info_protein_id,Info_pos,Info_AA,Info_pubmed_id,Info_epitope_id,Info_host_id,Info_nPos,Info_nNeg,...,feat_esm1b_1270,feat_esm1b_1271,feat_esm1b_1272,feat_esm1b_1273,feat_esm1b_1274,feat_esm1b_1275,feat_esm1b_1276,feat_esm1b_1277,feat_esm1b_1278,feat_esm1b_1279
0,P05877.1:3,11696,P05877.1,306,Y,"9289390,10368281,22164215,31263112","79327,163954,604752","9606,10090,9544","1,3,2,18","1,0,0,0",...,0.398270,-0.144087,-0.342332,0.051193,-1.169518,-0.304270,0.258099,-0.184203,-0.768978,0.095764
1,P05877.1:3,11696,P05877.1,307,N,"9289390,10368281,22164215,31263112","79327,163954,604752","9606,10090,9544","1,3,2,18","1,0,0,0",...,0.120641,0.036068,-0.711948,-0.052949,-0.642261,-0.595665,-0.107459,-0.188584,-0.662220,0.006413
2,P05877.1:3,11696,P05877.1,308,K,"9289390,10368281,16731948,20622876,22164215,31...","79327,163954,162763,162762,604752","9606,10090,9544","1,3,3,3,2,18","1,0,0,0,0,0",...,0.600361,0.278707,-0.306851,-0.416138,-0.714807,0.062856,0.357250,-0.051216,-0.043051,-0.218856
3,P05877.1:3,11696,P05877.1,309,R,"9289390,10368281,16731948,19913488,20622876,22...","79327,163954,162763,146524,162762,604752,780125","9606,10090,9544","1,3,3,2,3,2,6,18","1,0,0,0,0,0,0,0",...,0.497170,0.072447,-0.615481,0.075875,-0.763808,-0.348592,0.216759,0.066034,-0.236564,-0.308142
4,P05877.1:3,11696,P05877.1,310,K,"9289390,8327513,10368281,14592768,16731948,199...","79327,149350,163954,162761,162763,146524,16276...","9606,10000252,10090,9544","1,1,3,1,3,2,3,1,2,6,18,1","1,0,0,0,0,0,0,0,0,0,0,0",...,0.465172,0.006267,-0.526020,-0.084951,-0.724663,-0.206482,0.153864,-0.245701,-0.199443,-0.057272