In [1]:
import pandas as pd

taxonomy_keys = pd.read_csv('taxonomy_keys_10239.csv')
print(taxonomy_keys.shape)
taxonomy_keys.head()

(9, 7)

,ScientificName,Rank,UID,nPos,nNeg,nTot,IDs
0,Viruses,superkingdom,10239,6382,10201,16583,"11320,383586,387147,370128,387139,382832,39280..."
1,Riboviria,clade,2559587,4555,8544,13099,"11320,383586,387147,387139,382832,392809,38283..."
2,Pararnavirae,kingdom,2732397,410,188,598,"11780,11908,2169971,10408,10407,35269,11676,11..."
3,Artverviricota,phylum,2732409,410,188,598,"11780,11908,2169971,10408,10407,35269,11676,11..."
4,Revtraviricetes,class,2732514,410,188,598,"11780,11908,2169971,10408,10407,35269,11676,11..."

In [15]:
print(taxonomy_keys)

      ScientificName          Rank      UID  nPos   nNeg   nTot  \
0            Viruses  superkingdom    10239  6382  10201  16583
1          Riboviria         clade  2559587  4555   8544  13099
2       Pararnavirae       kingdom  2732397   410    188    598
3     Artverviricota        phylum  2732409   410    188    598
4    Revtraviricetes         class  2732514   410    188    598
5       Ortervirales         order  2169561   268    140    408
6       Retroviridae        family    11632   259    126    385
7  Orthoretrovirinae     subfamily   327045   234    116    350
8         Lentivirus         genus    11646    99     12    111

                                                 IDs
0  11320,383586,387147,370128,387139,382832,39280...
1  11320,383586,387147,387139,382832,392809,38283...
2  11780,11908,2169971,10408,10407,35269,11676,11...
3  11780,11908,2169971,10408,10407,35269,11676,11...
4  11780,11908,2169971,10408,10407,35269,11676,11...
5  11780,11908,2169971,11676,11864,11701,61673,11...
6  11780,11908,2169971,11676,11864,11701,61673,11...
7  11780,11908,2169971,11676,11864,11701,61673,11...
8  2169971,11676,11701,11661,11660,11674,11665,11...

In [16]:
lentivirusID_str = taxonomy_keys.iloc[8]['IDs']
print(lentivirusID_str)
lentivirusID = [id.strip() for id in lentivirusID_str.split(',')]
print(lentivirusID)

2169971,11676,11701,11661,11660,11674,11665,11671,45409,11696,254355,11743,36374,12750,11706,11691,11698,11678,11709,362651,11662,11688
['2169971', '11676', '11701', '11661', '11660', '11674', '11665', '11671', '45409', '11696', '254355', '11743', '36374', '12750', '11706', '11691', '11698', '11678', '11709', '362651', '11662', '11688']

In [18]:
data = pd.read_csv('all_virus_LBCE_with_ESM1b_features.csv', low_memory=False)
data.head()

,Info_PepID,Info_organism_id,Info_protein_id,Info_pos,Info_AA,Info_pubmed_id,Info_epitope_id,Info_host_id,Info_nPos,Info_nNeg,...,feat_esm1b_1270,feat_esm1b_1271,feat_esm1b_1272,feat_esm1b_1273,feat_esm1b_1274,feat_esm1b_1275,feat_esm1b_1276,feat_esm1b_1277,feat_esm1b_1278,feat_esm1b_1279
0,0704243A:2,11320,0704243A,46,S,2579329,61385,10000206,0,2,...,0.074220,-0.306854,-0.046597,0.096433,-1.108830,-0.199020,0.281864,0.003761,0.277273,0.178494
1,0704243A:2,11320,0704243A,47,S,2579329,61385,10000206,0,2,...,0.014104,-0.215472,-0.107374,0.239241,-1.127827,-0.281195,0.344047,0.069742,0.269180,0.259537
2,0704243A:2,11320,0704243A,48,T,2579329,61385,10000206,0,2,...,0.218574,-0.124948,0.082776,0.201489,-0.840510,-0.307259,0.154050,0.100896,0.307250,0.520543
3,0704243A:2,11320,0704243A,49,G,2579329,61385,10000206,0,2,...,0.200644,-0.233248,0.010473,0.070615,-0.804467,-0.219895,0.311264,0.220049,0.131534,0.247521
4,0704243A:2,11320,0704243A,50,K,2579329,61385,10000206,0,2,...,0.103338,-0.239433,0.117235,-0.019795,-1.173937,-0.133920,0.014691,0.156032,0.260330,0.197664

In [46]:
#lentivirus_data = data[data['Info_host_id'].isin(lentivirusID)]
#lentivirus_data.to_csv('lentivirus.csv', index=False)
#print(lentivirus_data)
peptide = pd.read_csv('peptides.csv')
peptide.head()

,Info_PepID,Info_organism_id,Info_host_id,Info_protein_id,Info_start_pos,Info_end_pos,Info_peptide,Info_peptide_length,Info_cluster,Info_split,Class,txid
0,0704243A:10,11320.0,10000000,0704243A,175,204,DKLYIWGVHHPSTNQEQTSLYVQASGRVTV,30,1,split_05_20,-1,11320.0
1,0704243A:12,11320.0,10000233,0704243A,208,214,RSQQTII,7,1,split_05_20,1,11320.0
2,0704243A:14,11320.0,9606,0704243A,227,239,SSRISIYWTIVKP,13,1,split_05_20,1,11320.0
3,0704243A:16,11320.0,10000206,0704243A,272,280,APIDTCISE,9,1,split_05_20,-1,11320.0
4,0704243A:18,11320.0,10000206,0704243A,305,328,CPKYVKQNTLKLATGMRNVPEKQT,24,1,split_05_20,1,11320.0

In [55]:
lentivirus_data = peptide[peptide['Info_organism_id'].isin(lentivirusID)]
print(lentivirus_data)
#lentivirus_data.to_csv('lentivirus.csv', index=False)

Empty DataFrame
Columns: [Info_PepID, Info_organism_id, Info_host_id, Info_protein_id, Info_start_pos, Info_end_pos, Info_peptide, Info_peptide_length, Info_cluster, Info_split, Class, txid]
Index: []

In [67]:
specific_value = 11688
if specific_value in data['Info_epitope_id'].values:
    print("Yes.")
else:
    print("No.")

No.

In [72]:
desired = ['11320']
matching_rows = data[data['Info_organism_id'].isin(desired)]
if not matching_rows.empty:
    # Rows with desired values found
    print(matching_rows)
else:
    # No rows with desired values found
    print("No matching rows found.")
print(matching_rows)

No matching rows found.
Empty DataFrame
Columns: [Info_PepID, Info_organism_id, Info_protein_id, Info_pos, Info_AA, Info_pubmed_id, Info_epitope_id, Info_host_id, Info_nPos, Info_nNeg, Info_type, Info_window, Info_cluster, Class, feat_esm1b_0, feat_esm1b_1, feat_esm1b_2, feat_esm1b_3, feat_esm1b_4, feat_esm1b_5, feat_esm1b_6, feat_esm1b_7, feat_esm1b_8, feat_esm1b_9, feat_esm1b_10, feat_esm1b_11, feat_esm1b_12, feat_esm1b_13, feat_esm1b_14, feat_esm1b_15, feat_esm1b_16, feat_esm1b_17, feat_esm1b_18, feat_esm1b_19, feat_esm1b_20, feat_esm1b_21, feat_esm1b_22, feat_esm1b_23, feat_esm1b_24, feat_esm1b_25, feat_esm1b_26, feat_esm1b_27, feat_esm1b_28, feat_esm1b_29, feat_esm1b_30, feat_esm1b_31, feat_esm1b_32, feat_esm1b_33, feat_esm1b_34, feat_esm1b_35, feat_esm1b_36, feat_esm1b_37, feat_esm1b_38, feat_esm1b_39, feat_esm1b_40, feat_esm1b_41, feat_esm1b_42, feat_esm1b_43, feat_esm1b_44, feat_esm1b_45, feat_esm1b_46, feat_esm1b_47, feat_esm1b_48, feat_esm1b_49, feat_esm1b_50, feat_esm1b_51, feat_esm1b_52, feat_esm1b_53, feat_esm1b_54, feat_esm1b_55, feat_esm1b_56, feat_esm1b_57, feat_esm1b_58, feat_esm1b_59, feat_esm1b_60, feat_esm1b_61, feat_esm1b_62, feat_esm1b_63, feat_esm1b_64, feat_esm1b_65, feat_esm1b_66, feat_esm1b_67, feat_esm1b_68, feat_esm1b_69, feat_esm1b_70, feat_esm1b_71, feat_esm1b_72, feat_esm1b_73, feat_esm1b_74, feat_esm1b_75, feat_esm1b_76, feat_esm1b_77, feat_esm1b_78, feat_esm1b_79, feat_esm1b_80, feat_esm1b_81, feat_esm1b_82, feat_esm1b_83, feat_esm1b_84, feat_esm1b_85, ...]
Index: []

[0 rows x 1294 columns]

In [75]:
unique_values = data['Info_organism_id'].unique()
print(unique_values)

[  11320  383586  387147  387139  382832  392809  382835  383571  150127
  384505   63106  444318  211044   11142  132504   11780   11292   11072
   12098   12107   11588   11295   11060   11079  301478   12082   11234
   11602  387161   11064   33741   11623  103929   11622   11053   10962
   39002   11296   10927  228330   63330   11103   11696  381516   88104
  130760  227984  333284   63746   11104   31645 1678143 2847144  356410
   31647  420174   31767   11116   10407   11105   11113   11115   12116
   31650   31768   31644  356426  356415   11110  329389   12072  103903
   40271   31649   54290   11662  356418  260806   35269   11908   12639
  138950   10410   73482   10430   11144   11676   12110  341946   11082
  128952   11096  229992 2560602   11901   39054   12092 2169971   11276
   10408   11235   11098   11084   11070   12064  421877   12118   11701
   11149  150846  489469   61673   11049   11661   11660   11048   12455
   11259   11246   11250  367120  130763  427773   11232   11243   11674
   12125   11260   11041   11926   11909  358769   46290   11045   11927
   11665   11671   12112   12120   28344   11795   82824   12073   45409
   11251   12067 2560319   10904   33717   11120   11256   11255  208893
   11253   11252  410078   11764   82639   12086   11812   11196   42782
  381513 1144025   41857   37137   10995  110195   11191   33747   10941
   94432   35288   12161  117204   12131   12081   40051   12242   12071
 2169986   12080  132487   11151   11135   12246  254355   11743   36374
   11942   12814   94967   12130   36409   11983  150080   12305   10923
   11824   12216   12115   12146   12088   11277   72539   12117   12063
   11217  292633   28295   37128   35329   31721   11062   11069   11150
   10900   10903   11241 1933300   12260   82823   10879   35330   31715
   55951 1980456 1980491  356411   12750   12211   65743   28375  358805
   45617   64382   11706  284218  644788  165512  381512  417758  447133
  461772   12077   12075  121791   11577  103905   11288  186540 2169991
   12162  392811   41856 2560580  228407  164326  303316  382781  223997
  648856 1980519  641501  194959  408686   11065   11691   11698  186538
   11138  336092  577543   11678  378830  307044   11080   11077  680692
  155220  680690  183741  404573   89172   89169  196462  172149  332747
  284202  506282  292039  292045   12132   31634   31704 1980481 1239567
   11066   11864   59375  421901   11709  183764  468968  754366  362651
  155218  432070  472511  427890  418868  357210  370811  414044  562988
  562992  464314  421472  411157  641812  402938  352764  162326  385585
  384510  380284  352564  359921  449656  371214  352034   35327  645724
  197780   11100  524364  565995  186539   11269   11790   11047   11620
 1133363   11059   38171  604436  504904  476294 1286616   10915  915014
   12060   12078   12232   11688   94966 1006061  266827  400828  161600
  284190  100835  292590  614035  510222   11215  642261  641809  464622
  380342  529058   63421   35331  382825  425551  632134  322053  270478
   29271   11976 1401444  506350   55097 1310532  453057  292349   12111
 1399582   64320   28875 1476909  328671  328670 1016853 1016852   36421
 1053141   53182   64293   11636  370810   33745 1406148   11083  647923
   42789 1570291  644289  279329  556277   42769   12637   11963  221703
 2170197 2170200 2170206 2170201   31708 1972699 1335626 1263720  269638
 1330520  479022  683780 2115988 1763596  707882  280855 1586324  138951
  229032 2697049  185894 1321999   12663  390157  195055  277944 1241973
  489821   11137   31631  443240  290028 2709072 2708335 1173018 1331831
 1968303 1968304 2026007 1914447  694007   11099   54315 1508227   11128
  443241  443239  694008   11590  408870   31635  408871   11089 1349999
  502101  454951 2032731  392172  122929   11624   11981  627442 1980494
   83192 1980485   46920   37207   42097 1980459 1980486   33727  195700
   11553  208726]

In [80]:
int_list = [int(x) for x in lentivirusID]
print(int_list)

[2169971, 11676, 11701, 11661, 11660, 11674, 11665, 11671, 45409, 11696, 254355, 11743, 36374, 12750, 11706, 11691, 11698, 11678, 11709, 362651, 11662, 11688]

In [87]:
#lentivirus_data = peptide[peptide['Info_organism_id'].isin(int_list)]
lentivirus_data = data[data['Info_organism_id'].isin(int_list)]
lentivirus_data.to_csv('lentivirus.csv', index=False)

In [91]:
data_lenti = pd.read_csv('lentivirus.csv', low_memory=False)
print(data_lenti.shape)
data_lenti.head()

(1795, 1294)

,Info_PepID,Info_organism_id,Info_protein_id,Info_pos,Info_AA,Info_pubmed_id,Info_epitope_id,Info_host_id,Info_nPos,Info_nNeg,...,feat_esm1b_1270,feat_esm1b_1271,feat_esm1b_1272,feat_esm1b_1273,feat_esm1b_1274,feat_esm1b_1275,feat_esm1b_1276,feat_esm1b_1277,feat_esm1b_1278,feat_esm1b_1279
0,P05877.1:3,11696,P05877.1,306,Y,"9289390,10368281,22164215,31263112","79327,163954,604752","9606,10090,9544","1,3,2,18","1,0,0,0",...,0.398270,-0.144087,-0.342332,0.051193,-1.169518,-0.304270,0.258099,-0.184203,-0.768978,0.095764
1,P05877.1:3,11696,P05877.1,307,N,"9289390,10368281,22164215,31263112","79327,163954,604752","9606,10090,9544","1,3,2,18","1,0,0,0",...,0.120641,0.036068,-0.711948,-0.052949,-0.642261,-0.595665,-0.107459,-0.188584,-0.662220,0.006413
2,P05877.1:3,11696,P05877.1,308,K,"9289390,10368281,16731948,20622876,22164215,31...","79327,163954,162763,162762,604752","9606,10090,9544","1,3,3,3,2,18","1,0,0,0,0,0",...,0.600361,0.278707,-0.306851,-0.416138,-0.714807,0.062856,0.357250,-0.051216,-0.043051,-0.218856
3,P05877.1:3,11696,P05877.1,309,R,"9289390,10368281,16731948,19913488,20622876,22...","79327,163954,162763,146524,162762,604752,780125","9606,10090,9544","1,3,3,2,3,2,6,18","1,0,0,0,0,0,0,0",...,0.497170,0.072447,-0.615481,0.075875,-0.763808,-0.348592,0.216759,0.066034,-0.236564,-0.308142
4,P05877.1:3,11696,P05877.1,310,K,"9289390,8327513,10368281,14592768,16731948,199...","79327,149350,163954,162761,162763,146524,16276...","9606,10000252,10090,9544","1,1,3,1,3,2,3,1,2,6,18,1","1,0,0,0,0,0,0,0,0,0,0,0",...,0.465172,0.006267,-0.526020,-0.084951,-0.724663,-0.206482,0.153864,-0.245701,-0.199443,-0.057272

In [95]:
data_lenti.dtypes

Info_PepID           object
Info_organism_id      int64
Info_protein_id      object
Info_pos              int64
Info_AA              object
                     ...
feat_esm1b_1275     float64
feat_esm1b_1276     float64
feat_esm1b_1277     float64
feat_esm1b_1278     float64
feat_esm1b_1279     float64
Length: 1294, dtype: object

In [96]:
data_lenti.isnull().sum()

Info_PepID          0
Info_organism_id    0
Info_protein_id     0
Info_pos            0
Info_AA             0
                   ..
feat_esm1b_1275     0
feat_esm1b_1276     0
feat_esm1b_1277     0
feat_esm1b_1278     0
feat_esm1b_1279     0
Length: 1294, dtype: int64

In [98]:
Total = data_lenti.isnull().sum().sort_values(ascending=False)          

Percent = (data_lenti.isnull().sum()*100/data_lenti.isnull().count()).sort_values(ascending=False)   

missing_data = pd.concat([Total, Percent], axis = 1, keys = ['Total', 'Percentage of Missing Values'])    
missing_data

                 Total  Percentage of Missing Values
Info_PepID           0                           0.0
feat_esm1b_875       0                           0.0
feat_esm1b_853       0                           0.0
feat_esm1b_852       0                           0.0
feat_esm1b_851       0                           0.0
...                ...                           ...
feat_esm1b_416       0                           0.0
feat_esm1b_415       0                           0.0
feat_esm1b_414       0                           0.0
feat_esm1b_413       0                           0.0
feat_esm1b_1279      0                           0.0

[1294 rows x 2 columns]